name: Format
on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn run format:check
