name: Format
on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn run format:check
